/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGmailRouteImport } from './routes/_app.gmail'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActionCenterRouteImport } from './routes/_app.action-center'
import { Route as AppGmailOverviewRouteImport } from './routes/_app.gmail_.overview'
import { Route as AppGmailInboxRouteImport } from './routes/_app.gmail_.inbox'
import { Route as AppIntegrationsLinkedinSetupRouteImport } from './routes/_app.integrations.linkedin.setup'
import { Route as AppIntegrationsLinkedinManageRouteImport } from './routes/_app.integrations.linkedin.manage'
import { Route as AppIntegrationsInstagramSetupRouteImport } from './routes/_app.integrations.instagram.setup'
import { Route as AppIntegrationsInstagramManageRouteImport } from './routes/_app.integrations.instagram.manage'
import { Route as AppIntegrationsGmailSetupRouteImport } from './routes/_app.integrations.gmail.setup'
import { Route as AppIntegrationsGmailManageRouteImport } from './routes/_app.integrations.gmail.manage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGmailRoute = AppGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActionCenterRoute = AppActionCenterRouteImport.update({
  id: '/action-center',
  path: '/action-center',
  getParentRoute: () => AppRoute,
} as any)
const AppGmailOverviewRoute = AppGmailOverviewRouteImport.update({
  id: '/gmail_/overview',
  path: '/gmail/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppGmailInboxRoute = AppGmailInboxRouteImport.update({
  id: '/gmail_/inbox',
  path: '/gmail/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsLinkedinSetupRoute =
  AppIntegrationsLinkedinSetupRouteImport.update({
    id: '/integrations/linkedin/setup',
    path: '/integrations/linkedin/setup',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsLinkedinManageRoute =
  AppIntegrationsLinkedinManageRouteImport.update({
    id: '/integrations/linkedin/manage',
    path: '/integrations/linkedin/manage',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsInstagramSetupRoute =
  AppIntegrationsInstagramSetupRouteImport.update({
    id: '/integrations/instagram/setup',
    path: '/integrations/instagram/setup',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsInstagramManageRoute =
  AppIntegrationsInstagramManageRouteImport.update({
    id: '/integrations/instagram/manage',
    path: '/integrations/instagram/manage',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsGmailSetupRoute =
  AppIntegrationsGmailSetupRouteImport.update({
    id: '/integrations/gmail/setup',
    path: '/integrations/gmail/setup',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsGmailManageRoute =
  AppIntegrationsGmailManageRouteImport.update({
    id: '/integrations/gmail/manage',
    path: '/integrations/gmail/manage',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-center': typeof AppActionCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/contacts': typeof AppContactsRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/gmail': typeof AppGmailRoute
  '/home': typeof AppHomeRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/gmail/inbox': typeof AppGmailInboxRoute
  '/gmail/overview': typeof AppGmailOverviewRoute
  '/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/integrations/gmail/setup': typeof AppIntegrationsGmailSetupRoute
  '/integrations/instagram/manage': typeof AppIntegrationsInstagramManageRoute
  '/integrations/instagram/setup': typeof AppIntegrationsInstagramSetupRoute
  '/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
  '/integrations/linkedin/setup': typeof AppIntegrationsLinkedinSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-center': typeof AppActionCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/contacts': typeof AppContactsRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/gmail': typeof AppGmailRoute
  '/home': typeof AppHomeRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/gmail/inbox': typeof AppGmailInboxRoute
  '/gmail/overview': typeof AppGmailOverviewRoute
  '/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/integrations/gmail/setup': typeof AppIntegrationsGmailSetupRoute
  '/integrations/instagram/manage': typeof AppIntegrationsInstagramManageRoute
  '/integrations/instagram/setup': typeof AppIntegrationsInstagramSetupRoute
  '/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
  '/integrations/linkedin/setup': typeof AppIntegrationsLinkedinSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/action-center': typeof AppActionCenterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gmail': typeof AppGmailRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/gmail_/inbox': typeof AppGmailInboxRoute
  '/_app/gmail_/overview': typeof AppGmailOverviewRoute
  '/_app/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/_app/integrations/gmail/setup': typeof AppIntegrationsGmailSetupRoute
  '/_app/integrations/instagram/manage': typeof AppIntegrationsInstagramManageRoute
  '/_app/integrations/instagram/setup': typeof AppIntegrationsInstagramSetupRoute
  '/_app/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
  '/_app/integrations/linkedin/setup': typeof AppIntegrationsLinkedinSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-center'
    | '/analytics'
    | '/calendar'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/gmail'
    | '/home'
    | '/opportunities'
    | '/overview'
    | '/settings'
    | '/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/gmail/inbox'
    | '/gmail/overview'
    | '/integrations/gmail/manage'
    | '/integrations/gmail/setup'
    | '/integrations/instagram/manage'
    | '/integrations/instagram/setup'
    | '/integrations/linkedin/manage'
    | '/integrations/linkedin/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-center'
    | '/analytics'
    | '/calendar'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/gmail'
    | '/home'
    | '/opportunities'
    | '/overview'
    | '/settings'
    | '/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/gmail/inbox'
    | '/gmail/overview'
    | '/integrations/gmail/manage'
    | '/integrations/gmail/setup'
    | '/integrations/instagram/manage'
    | '/integrations/instagram/setup'
    | '/integrations/linkedin/manage'
    | '/integrations/linkedin/setup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/action-center'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/contacts'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/gmail'
    | '/_app/home'
    | '/_app/opportunities'
    | '/_app/overview'
    | '/_app/settings'
    | '/_app/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/_app/gmail_/inbox'
    | '/_app/gmail_/overview'
    | '/_app/integrations/gmail/manage'
    | '/_app/integrations/gmail/setup'
    | '/_app/integrations/instagram/manage'
    | '/_app/integrations/instagram/setup'
    | '/_app/integrations/linkedin/manage'
    | '/_app/integrations/linkedin/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gmail': {
      id: '/_app/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof AppGmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-center': {
      id: '/_app/action-center'
      path: '/action-center'
      fullPath: '/action-center'
      preLoaderRoute: typeof AppActionCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gmail_/overview': {
      id: '/_app/gmail_/overview'
      path: '/gmail/overview'
      fullPath: '/gmail/overview'
      preLoaderRoute: typeof AppGmailOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gmail_/inbox': {
      id: '/_app/gmail_/inbox'
      path: '/gmail/inbox'
      fullPath: '/gmail/inbox'
      preLoaderRoute: typeof AppGmailInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/linkedin/setup': {
      id: '/_app/integrations/linkedin/setup'
      path: '/integrations/linkedin/setup'
      fullPath: '/integrations/linkedin/setup'
      preLoaderRoute: typeof AppIntegrationsLinkedinSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/linkedin/manage': {
      id: '/_app/integrations/linkedin/manage'
      path: '/integrations/linkedin/manage'
      fullPath: '/integrations/linkedin/manage'
      preLoaderRoute: typeof AppIntegrationsLinkedinManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/instagram/setup': {
      id: '/_app/integrations/instagram/setup'
      path: '/integrations/instagram/setup'
      fullPath: '/integrations/instagram/setup'
      preLoaderRoute: typeof AppIntegrationsInstagramSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/instagram/manage': {
      id: '/_app/integrations/instagram/manage'
      path: '/integrations/instagram/manage'
      fullPath: '/integrations/instagram/manage'
      preLoaderRoute: typeof AppIntegrationsInstagramManageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/gmail/setup': {
      id: '/_app/integrations/gmail/setup'
      path: '/integrations/gmail/setup'
      fullPath: '/integrations/gmail/setup'
      preLoaderRoute: typeof AppIntegrationsGmailSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/gmail/manage': {
      id: '/_app/integrations/gmail/manage'
      path: '/integrations/gmail/manage'
      fullPath: '/integrations/gmail/manage'
      preLoaderRoute: typeof AppIntegrationsGmailManageRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionCenterRoute: typeof AppActionCenterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppContactsRoute: typeof AppContactsRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGmailRoute: typeof AppGmailRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppGmailInboxRoute: typeof AppGmailInboxRoute
  AppGmailOverviewRoute: typeof AppGmailOverviewRoute
  AppIntegrationsGmailManageRoute: typeof AppIntegrationsGmailManageRoute
  AppIntegrationsGmailSetupRoute: typeof AppIntegrationsGmailSetupRoute
  AppIntegrationsInstagramManageRoute: typeof AppIntegrationsInstagramManageRoute
  AppIntegrationsInstagramSetupRoute: typeof AppIntegrationsInstagramSetupRoute
  AppIntegrationsLinkedinManageRoute: typeof AppIntegrationsLinkedinManageRoute
  AppIntegrationsLinkedinSetupRoute: typeof AppIntegrationsLinkedinSetupRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionCenterRoute: AppActionCenterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppContactsRoute: AppContactsRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGmailRoute: AppGmailRoute,
  AppHomeRoute: AppHomeRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppGmailInboxRoute: AppGmailInboxRoute,
  AppGmailOverviewRoute: AppGmailOverviewRoute,
  AppIntegrationsGmailManageRoute: AppIntegrationsGmailManageRoute,
  AppIntegrationsGmailSetupRoute: AppIntegrationsGmailSetupRoute,
  AppIntegrationsInstagramManageRoute: AppIntegrationsInstagramManageRoute,
  AppIntegrationsInstagramSetupRoute: AppIntegrationsInstagramSetupRoute,
  AppIntegrationsLinkedinManageRoute: AppIntegrationsLinkedinManageRoute,
  AppIntegrationsLinkedinSetupRoute: AppIntegrationsLinkedinSetupRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
