/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGmailRouteImport } from './routes/_app.gmail'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActionCenterRouteImport } from './routes/_app.action-center'
import { Route as AppIntegrationsLinkedinRouteImport } from './routes/_app.integrations.linkedin'
import { Route as AppIntegrationsInstagramRouteImport } from './routes/_app.integrations.instagram'
import { Route as AppIntegrationsGmailRouteImport } from './routes/_app.integrations.gmail'
import { Route as AppIntegrationsLinkedinManageRouteImport } from './routes/_app.integrations.linkedin.manage'
import { Route as AppIntegrationsGmailManageRouteImport } from './routes/_app.integrations.gmail.manage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGmailRoute = AppGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActionCenterRoute = AppActionCenterRouteImport.update({
  id: '/action-center',
  path: '/action-center',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsLinkedinRoute = AppIntegrationsLinkedinRouteImport.update({
  id: '/integrations/linkedin',
  path: '/integrations/linkedin',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsInstagramRoute =
  AppIntegrationsInstagramRouteImport.update({
    id: '/integrations/instagram',
    path: '/integrations/instagram',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsGmailRoute = AppIntegrationsGmailRouteImport.update({
  id: '/integrations/gmail',
  path: '/integrations/gmail',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsLinkedinManageRoute =
  AppIntegrationsLinkedinManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AppIntegrationsLinkedinRoute,
  } as any)
const AppIntegrationsGmailManageRoute =
  AppIntegrationsGmailManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AppIntegrationsGmailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-center': typeof AppActionCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/contacts': typeof AppContactsRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/gmail': typeof AppGmailRoute
  '/home': typeof AppHomeRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/integrations/gmail': typeof AppIntegrationsGmailRouteWithChildren
  '/integrations/instagram': typeof AppIntegrationsInstagramRoute
  '/integrations/linkedin': typeof AppIntegrationsLinkedinRouteWithChildren
  '/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-center': typeof AppActionCenterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/contacts': typeof AppContactsRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/gmail': typeof AppGmailRoute
  '/home': typeof AppHomeRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/settings': typeof AppSettingsRoute
  '/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/integrations/gmail': typeof AppIntegrationsGmailRouteWithChildren
  '/integrations/instagram': typeof AppIntegrationsInstagramRoute
  '/integrations/linkedin': typeof AppIntegrationsLinkedinRouteWithChildren
  '/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/action-center': typeof AppActionCenterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gmail': typeof AppGmailRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/integrations/gmail': typeof AppIntegrationsGmailRouteWithChildren
  '/_app/integrations/instagram': typeof AppIntegrationsInstagramRoute
  '/_app/integrations/linkedin': typeof AppIntegrationsLinkedinRouteWithChildren
  '/_app/integrations/gmail/manage': typeof AppIntegrationsGmailManageRoute
  '/_app/integrations/linkedin/manage': typeof AppIntegrationsLinkedinManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-center'
    | '/analytics'
    | '/calendar'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/gmail'
    | '/home'
    | '/opportunities'
    | '/settings'
    | '/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/integrations/gmail'
    | '/integrations/instagram'
    | '/integrations/linkedin'
    | '/integrations/gmail/manage'
    | '/integrations/linkedin/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-center'
    | '/analytics'
    | '/calendar'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/gmail'
    | '/home'
    | '/opportunities'
    | '/settings'
    | '/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/integrations/gmail'
    | '/integrations/instagram'
    | '/integrations/linkedin'
    | '/integrations/gmail/manage'
    | '/integrations/linkedin/manage'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/action-center'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/contacts'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/gmail'
    | '/_app/home'
    | '/_app/opportunities'
    | '/_app/settings'
    | '/_app/workspace'
    | '/auth/login'
    | '/auth/register'
    | '/_app/integrations/gmail'
    | '/_app/integrations/instagram'
    | '/_app/integrations/linkedin'
    | '/_app/integrations/gmail/manage'
    | '/_app/integrations/linkedin/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gmail': {
      id: '/_app/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof AppGmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/action-center': {
      id: '/_app/action-center'
      path: '/action-center'
      fullPath: '/action-center'
      preLoaderRoute: typeof AppActionCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/linkedin': {
      id: '/_app/integrations/linkedin'
      path: '/integrations/linkedin'
      fullPath: '/integrations/linkedin'
      preLoaderRoute: typeof AppIntegrationsLinkedinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/instagram': {
      id: '/_app/integrations/instagram'
      path: '/integrations/instagram'
      fullPath: '/integrations/instagram'
      preLoaderRoute: typeof AppIntegrationsInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/gmail': {
      id: '/_app/integrations/gmail'
      path: '/integrations/gmail'
      fullPath: '/integrations/gmail'
      preLoaderRoute: typeof AppIntegrationsGmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/linkedin/manage': {
      id: '/_app/integrations/linkedin/manage'
      path: '/manage'
      fullPath: '/integrations/linkedin/manage'
      preLoaderRoute: typeof AppIntegrationsLinkedinManageRouteImport
      parentRoute: typeof AppIntegrationsLinkedinRoute
    }
    '/_app/integrations/gmail/manage': {
      id: '/_app/integrations/gmail/manage'
      path: '/manage'
      fullPath: '/integrations/gmail/manage'
      preLoaderRoute: typeof AppIntegrationsGmailManageRouteImport
      parentRoute: typeof AppIntegrationsGmailRoute
    }
  }
}

interface AppIntegrationsGmailRouteChildren {
  AppIntegrationsGmailManageRoute: typeof AppIntegrationsGmailManageRoute
}

const AppIntegrationsGmailRouteChildren: AppIntegrationsGmailRouteChildren = {
  AppIntegrationsGmailManageRoute: AppIntegrationsGmailManageRoute,
}

const AppIntegrationsGmailRouteWithChildren =
  AppIntegrationsGmailRoute._addFileChildren(AppIntegrationsGmailRouteChildren)

interface AppIntegrationsLinkedinRouteChildren {
  AppIntegrationsLinkedinManageRoute: typeof AppIntegrationsLinkedinManageRoute
}

const AppIntegrationsLinkedinRouteChildren: AppIntegrationsLinkedinRouteChildren =
  {
    AppIntegrationsLinkedinManageRoute: AppIntegrationsLinkedinManageRoute,
  }

const AppIntegrationsLinkedinRouteWithChildren =
  AppIntegrationsLinkedinRoute._addFileChildren(
    AppIntegrationsLinkedinRouteChildren,
  )

interface AppRouteChildren {
  AppActionCenterRoute: typeof AppActionCenterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppContactsRoute: typeof AppContactsRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGmailRoute: typeof AppGmailRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIntegrationsGmailRoute: typeof AppIntegrationsGmailRouteWithChildren
  AppIntegrationsInstagramRoute: typeof AppIntegrationsInstagramRoute
  AppIntegrationsLinkedinRoute: typeof AppIntegrationsLinkedinRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppActionCenterRoute: AppActionCenterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppContactsRoute: AppContactsRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGmailRoute: AppGmailRoute,
  AppHomeRoute: AppHomeRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIntegrationsGmailRoute: AppIntegrationsGmailRouteWithChildren,
  AppIntegrationsInstagramRoute: AppIntegrationsInstagramRoute,
  AppIntegrationsLinkedinRoute: AppIntegrationsLinkedinRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
